source system perl generatefinnair2.pl 2;
source system perl generateklm2.pl 2;
source system perl generatelufthansa2.pl 2;
USE FINNAIR;
DROP TABLE BOOKINGS;
DROP TABLE FLIGHTS;
DROP TABLE REFERENCENUMBERS;
DROP TABLE HELICOPTERPORTS;
source finnair.sql;
source finnairtableinfo.sql;
INSERT INTO HELICOPTERPORTS (flight_Id, ipAdress,port) VALUES (1,"127.0.0.1",55000); 
USE KLM;
DROP TABLE BOOKINGS;
DROP TABLE FLIGHTS;
DROP TABLE REFERENCENUMBERS;
DROP TABLE HELICOPTERPORTS; 
source finnair.sql;
source klmtableinfo.sql;
INSERT INTO HELICOPTERPORTS (flight_Id, ipAdress,port) VALUES (1,"127.0.0.1",56000); 
USE LUFTHANSA;
DROP TABLE BOOKINGS;
DROP TABLE FLIGHTS;
DROP TABLE REFERENCENUMBERS;
DROP TABLE HELICOPTERPORTS; 
source finnair.sql;
source lufthansatableinfo.sql;
INSERT INTO HELICOPTERPORTS (flight_Id, ipAdress,port) VALUES (1,"127.0.0.1",57000); 
USE FINNAIR; 